/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.GUI;
import deepspace.EnemyToUI;
/**
 *
 * @author diegoos_03
 */
public class EnemyView extends javax.swing.JPanel {

    private LootView loot_view;
    private DamageView damage_view;
    /**
     * Creates new form EnemyView
     */
    public EnemyView() {
        initComponents();
        
        loot_view = new LootView();
        add(loot_view);
        
        damage_view = new DamageView();
        add(damage_view);
    }
    
    public void setEnemyView(EnemyToUI e){
        
        Enemigo.setText(e.getName());
        Potencia_fuego.setText(Float.toString(e.getAmmoPower()));
        Potencia_escudo.setText(Float.toString(e.getShieldPower()));
        
        loot_view.setLootView(e.getLoot());
        damage_view.setDamageView(e.getDamage());
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Enemigo = new javax.swing.JLabel();
        Potencia_fuego = new javax.swing.JLabel();
        Potencia_escudo = new javax.swing.JLabel();
        Botín = new javax.swing.JPanel();
        Daño = new javax.swing.JPanel();

        Enemigo.setText("Enemigo:");

        Potencia_fuego.setText("Potencia de fuego:");

        Potencia_escudo.setText("Potencia de defensa:");

        Botín.setBorder(javax.swing.BorderFactory.createTitledBorder("Botín"));

        Daño.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Daño", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        javax.swing.GroupLayout DañoLayout = new javax.swing.GroupLayout(Daño);
        Daño.setLayout(DañoLayout);
        DañoLayout.setHorizontalGroup(
            DañoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DañoLayout.setVerticalGroup(
            DañoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Potencia_escudo)
                            .addComponent(Potencia_fuego)
                            .addComponent(Enemigo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Daño, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Botín, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Enemigo)
                .addGap(18, 18, 18)
                .addComponent(Potencia_fuego)
                .addGap(18, 18, 18)
                .addComponent(Potencia_escudo)
                .addGap(18, 18, 18)
                .addComponent(Botín, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Daño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Botín;
    private javax.swing.JPanel Daño;
    private javax.swing.JLabel Enemigo;
    private javax.swing.JLabel Potencia_escudo;
    private javax.swing.JLabel Potencia_fuego;
    // End of variables declaration//GEN-END:variables
}
