/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.GUI;

import deepspace.HangarToUI;
import deepspace.WeaponToUI;
import deepspace.ShieldToUI;
import java.awt.Component;
import java.util.ArrayList;

/**
 *
 * @author diegoos_03
 */
public class HangarView extends javax.swing.JPanel {

    /**
     * Creates new form HangarView
     */
    public HangarView() {
        initComponents();
    }
    
    public void setHangarView(HangarToUI h){
        
        setBorder(javax.swing.BorderFactory.createTitledBorder("Hangar con " + 
                            Integer.toString(h.getMaxElements()) + " lugares"));
        
        Interior.removeAll();
        ArrayList<WeaponToUI> w;
        ArrayList<ShieldToUI> s;
        
        w = h.getWeapons();
        s = h.getShieldBoosters();
        
        WeaponView wv;
        for(WeaponToUI weapon : w){
            wv = new WeaponView();
            wv.setWeaponView(weapon);
            Interior.add(wv);
        }
        
        ShieldView sv;
        for(ShieldToUI shield : s){
            sv = new ShieldView();
            sv.setShieldView(shield);
            Interior.add(sv);
        }
        
        repaint();
        revalidate();
    }

    public ArrayList<Integer> getSelectedBoxes () {
        ArrayList<Integer> selectedBoxes = new ArrayList<>();
        int i = 0;
        for (Component c : Interior.getComponents()) {
            if (((ShieldView) c).isSelected()) {
                selectedBoxes.add(i);
            }
            i++;
        }
        return selectedBoxes;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScrollWeapons = new javax.swing.JScrollPane();
        InteriorWeapons = new javax.swing.JPanel();
        ScrollShields = new javax.swing.JScrollPane();
        InteriorShields = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Hangar"));

        ScrollWeapons.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        ScrollWeapons.setPreferredSize(new java.awt.Dimension(378, 120));

        InteriorWeapons.setBorder(javax.swing.BorderFactory.createTitledBorder("Armas"));
        ScrollWeapons.setViewportView(InteriorWeapons);

        InteriorShields.setBorder(javax.swing.BorderFactory.createTitledBorder("Escudos"));
        ScrollShields.setViewportView(InteriorShields);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollWeapons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ScrollShields))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(ScrollWeapons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(ScrollShields, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel InteriorShields;
    private javax.swing.JPanel InteriorWeapons;
    private javax.swing.JScrollPane ScrollShields;
    private javax.swing.JScrollPane ScrollWeapons;
    // End of variables declaration//GEN-END:variables
}
