/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.GUI;

import deepspace.HangarToUI;
import deepspace.WeaponToUI;
import deepspace.ShieldToUI;
import java.util.ArrayList;

/**
 *
 * @author diegoos_03
 */
public class HangarView extends javax.swing.JPanel {

    /**
     * Creates new form HangarView
     */
    public HangarView() {
        initComponents();
    }
    
    public void setShieldsView(HangarToUI h){
        
        setBorder(javax.swing.BorderFactory.createTitledBorder("Hangar con " + 
                            Integer.toString(h.getMaxElements()) + " lugares"));
        
        Interior.removeAll();
        ArrayList<WeaponToUI> w;
        ArrayList<ShieldToUI> s;
        
        w = h.getWeapons();
        s = h.getShieldBoosters();
        
        WeaponView wv;
        for(WeaponToUI weapon : w){
            wv = new WeaponView();
            wv.setWeaponView(weapon);
            Interior.add(wv);
        }
        
        ShieldView sv;
        for(ShieldToUI shield : s){
            sv = new ShieldView();
            sv.setShieldView(shield);
            Interior.add(sv);
        }
        
        repaint();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Scroll = new javax.swing.JScrollPane();
        Interior = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Hangar"));

        Scroll.setViewportView(Interior);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Scroll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Interior;
    private javax.swing.JScrollPane Scroll;
    // End of variables declaration//GEN-END:variables
}
