/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package View.GUI;
import View.View;
import controller.Controller;
import controller.ControllerGUI;
import deepspace.GameUniverseToUI;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author gonzalomp
 */
public class MainWindow extends javax.swing.JFrame implements View {
    
    private static MainWindow instance = null;
    private static GameUniverseToUI gameUI;
    public static MainWindow getInstance (){
        if(instance == null)
            instance = new MainWindow();
        
        return instance;
    }
    /** Creates new form MainWindow */
    public MainWindow(){
        initComponents();
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                ControllerGUI.getInstance().finish(0);
            }
        });
    }  
    
    public void updateView(){
        gameUI = ControllerGUI.getInstance().getUIversion();
        SpaceStationView currentSS = new SpaceStationView();
        EnemyView currentEn = new EnemyView();
        
        currentEn.setEnemyView(gameUI.getCurrentEnemy());
        currentSS.setSpaceStationView(gameUI.getCurrentStation());
        
        currentStation.add(currentSS);
        currentEnemy.add(currentEn);
        
        repaint();
        revalidate();
    };
    
    public void showView() {
        this.setVisible(true);
    }
    
    @Override
    public ArrayList<String> getNames() {
        NamesCapture namesCapt = new NamesCapture(this);
        return namesCapt.getNames();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPruebas = new javax.swing.JPanel();
        currentStation = new javax.swing.JPanel();
        currentEnemy = new javax.swing.JPanel();
        Combatir = new javax.swing.JButton();
        Siguiente = new javax.swing.JButton();
        Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DeepSpace V1.0");
        setMinimumSize(new java.awt.Dimension(480, 480));

        panelPruebas.setMinimumSize(new java.awt.Dimension(900, 600));
        panelPruebas.setPreferredSize(new java.awt.Dimension(1080, 720));

        currentStation.setPreferredSize(new java.awt.Dimension(660, 810));

        currentEnemy.setPreferredSize(new java.awt.Dimension(550, 500));

        Combatir.setBackground(new java.awt.Color(51, 153, 255));
        Combatir.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        Combatir.setForeground(new java.awt.Color(204, 255, 255));
        Combatir.setText("COMBATIR");
        Combatir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CombatirActionPerformed(evt);
            }
        });

        Siguiente.setBackground(new java.awt.Color(51, 153, 255));
        Siguiente.setForeground(new java.awt.Color(204, 255, 255));
        Siguiente.setText("Siguiente turno");
        Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteActionPerformed(evt);
            }
        });

        Salir.setBackground(new java.awt.Color(255, 0, 0));
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPruebasLayout = new javax.swing.GroupLayout(panelPruebas);
        panelPruebas.setLayout(panelPruebasLayout);
        panelPruebasLayout.setHorizontalGroup(
            panelPruebasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPruebasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(currentStation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelPruebasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(currentEnemy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPruebasLayout.createSequentialGroup()
                        .addComponent(Combatir)
                        .addGap(31, 31, 31)
                        .addGroup(panelPruebasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Salir)
                            .addComponent(Siguiente)))))
        );
        panelPruebasLayout.setVerticalGroup(
            panelPruebasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPruebasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPruebasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPruebasLayout.createSequentialGroup()
                        .addComponent(currentEnemy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134)
                        .addGroup(panelPruebasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Combatir)
                            .addComponent(Siguiente))
                        .addGap(18, 18, 18)
                        .addComponent(Salir))
                    .addComponent(currentStation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(panelPruebas, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CombatirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CombatirActionPerformed
        // TODO add your handling code here:
        Controller.getInstance().combat();
        MainWindow.getInstance().updateView();
    }//GEN-LAST:event_CombatirActionPerformed

    private void SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteActionPerformed
        // TODO add your handling code here:
        Controller.getInstance().nextTurn();
        MainWindow.getInstance().updateView();
    }//GEN-LAST:event_SiguienteActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        Controller.getInstance().finish(0);
    }//GEN-LAST:event_SalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Combatir;
    private javax.swing.JButton Salir;
    private javax.swing.JButton Siguiente;
    private javax.swing.JPanel currentEnemy;
    private javax.swing.JPanel currentStation;
    private javax.swing.JPanel panelPruebas;
    // End of variables declaration//GEN-END:variables

}
