/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package View.GUI;
import View.View;
import controller.ControllerGUI;
import deepspace.GameUniverse;
import deepspace.WeaponToUI;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author gonzalomp
 */
public class MainWindow extends javax.swing.JFrame implements View {
    
    private static MainWindow instance = null;
    public static MainWindow getInstance (){
        if(instance == null)
            instance = new MainWindow();
        
        return instance;
    }
    /** Creates new form MainWindow */
    public MainWindow(){
        initComponents();
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                ControllerGUI.getInstance().finish(0);
            }
        });
    }  
    
    public void updateView(){
        
        repaint();
        revalidate();
    };
    
    public void showView() {
        this.setVisible(true);
    }
    
    @Override
    public ArrayList<String> getNames() {
        NamesCapture namesCapt = new NamesCapture(this);
        return namesCapt.getNames();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPruebas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DeepSpace V1.0");
        setMinimumSize(new java.awt.Dimension(480, 480));
        getContentPane().add(panelPruebas, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelPruebas;
    // End of variables declaration//GEN-END:variables

}
