/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.GUI;

import deepspace.ShieldToUI;
import java.awt.Component;
import java.util.ArrayList;

/**
 *
 * @author diegoos_03
 */
public class ShieldsView extends javax.swing.JPanel {

    /**
     * Creates new form ShieldsView
     */
    public ShieldsView() {
        initComponents();
    }
    
    public void setShieldsView(ArrayList<ShieldToUI> s){
        
        Interior.removeAll();
        ShieldView sv;
        
        for(ShieldToUI shield : s){
            sv = new ShieldView();
            sv.setShieldView(shield);
            Interior.add(sv);
        }
        
        repaint();
        revalidate();
    }

    public ArrayList<Integer> getSelectedBoxes () {
        ArrayList<Integer> selectedBoxes = new ArrayList<>();
        int i = 0;
        for (Component c : Interior.getComponents()) {
            if (((ShieldView) c).isSelected()) {
                selectedBoxes.add(i);
            }
            i++;
        }
        return selectedBoxes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Scroll = new javax.swing.JScrollPane();
        Interior = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Potenciadores de defensa"));

        Scroll.setViewportView(Interior);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Scroll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Interior;
    private javax.swing.JScrollPane Scroll;
    // End of variables declaration//GEN-END:variables
}
