/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.GUI;

import deepspace.WeaponToUI;
import java.awt.Component;
import java.util.ArrayList;

/**
 *
 * @author diegoos_03
 */
public class WeaponsView extends javax.swing.JPanel {

    /**
     * Creates new form WeaponsView
     */
    public WeaponsView() {
        initComponents();
    }
    
    public void setWeaponsView(ArrayList<WeaponToUI> w){
        
        Interior.removeAll();
        WeaponView wv;
        
        for(WeaponToUI weapon : w){
            wv = new WeaponView();
            wv.setWeaponView(weapon);
            Interior.add(wv);
        }
        
        repaint();
        revalidate();
    }
    
    public ArrayList<Integer> getSelectedBoxes () {
        ArrayList<Integer> selectedBoxes = new ArrayList<>();
        int i = 0;
        for (Component c : Interior.getComponents()) {
            if (((WeaponView) c).isSelected()) {
                selectedBoxes.add(i);
            }
            i++;
        }
        return selectedBoxes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Scroll = new javax.swing.JScrollPane();
        Interior = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Potenciadores de fuego"));
        setLayout(new java.awt.BorderLayout());

        Scroll.setViewportView(Interior);

        add(Scroll, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Interior;
    private javax.swing.JScrollPane Scroll;
    // End of variables declaration//GEN-END:variables
}
