/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.GUI;

import deepspace.WeaponToUI;
import java.awt.Color;
/**
 *
 * @author diegoos_03
 */
public class WeaponView extends javax.swing.JPanel {
    
    private boolean selected = false;
    /**
     * Creates new form WeaponView
     */
    public WeaponView() {
        initComponents(); 
        
        /*
        Tipo.setText("Tipo: " + w.getType().toString());
        Potencia.setText("Potencia: " + Float.toString(w.getPower()));
        Usos.setText("Usos: " + Integer.toString(w.getUses()));
        */
    }
    
    public void setWeaponView(WeaponToUI w){
        
        Tipo.setText("Tipo: " + w.getType().toString());
        Potencia.setText("Potencia: " + Float.toString(w.getPower()));
        Usos.setText("Usos: " + Integer.toString(w.getUses()));
        repaint();
    }
    
    public boolean isSelected(){ return selected; }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tipo = new javax.swing.JLabel();
        Potencia = new javax.swing.JLabel();
        Usos = new javax.swing.JLabel();

        setBackground(java.awt.Color.lightGray);
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMaximumSize(new java.awt.Dimension(200, 100));
        setPreferredSize(new java.awt.Dimension(120, 95));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        Tipo.setText("Tipo:");

        Potencia.setText("Potencia:");

        Usos.setText("Usos:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tipo)
                    .addComponent(Potencia)
                    .addComponent(Usos))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(Tipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Potencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Usos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        selected = !selected;
        setBackground (Color.BLUE);
        repaint();
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Potencia;
    private javax.swing.JLabel Tipo;
    private javax.swing.JLabel Usos;
    // End of variables declaration//GEN-END:variables
}
